development:
  adapter: postgresql
  encoding: unicode
  database: airdojo_development
  pool: 5
  username: postgres
  password: password
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: airdojo_test
  pool: 5
  username: postgres
  password: password
  host: localhost


production:
  adapter: postgresql
  encoding: unicode
  database: airdojo_production
  pool: 5
  username: postgres
  password: password
  host: localhost